name: stupid
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      
      - name: get date
        id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
        shell: bash

      - name: cache global directory
        uses: actions/cache@v4
        with:
          path: .
          key: buildozer-global-${{ hashFiles('buildozer.spec') }} # Replace with your path

      - uses: actions/cache@v4
        with:
          path: .buildozer
          key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('buildozer.spec') }}

      - name: build
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: pip3 install --user --upgrade cython==0.29.33 virtualenv; buildozer android debug
          buildozer_version: git+https://github.com/kivy/buildozer.git@master

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}
