name: android build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build with buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: build
        with:
          workdir: .
          buildozer_version: git+https://github.com/kivy/buildozer.git@master

      - name: upload apk
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: ${{ steps.build.outputs.filename }}
